/*
 * Smilr API
 *
 * Smilr microservice, RESTful data API
 *
 * OpenAPI spec version: 6.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using IO.Swagger.Attributes;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using ProblemDetails = IO.Swagger.Models.ProblemDetails;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class FeedbackApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This submit new feedback</remarks>
        /// <param name="feedback">The feedback to submit</param>
        /// <response code="200">Feedback object with id</response>
        /// <response code="400">Validation error with feedback</response>
        /// <response code="500">Unexpected error</response>
        [HttpPost]
        [Route("/api/feedback")]
        [ValidateModelState]
        [SwaggerOperation("FeedbackCreate")]
        [SwaggerResponse(statusCode: 200, type: typeof(Feedback), description: "Feedback object with id")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Validation error with feedback")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Unexpected error")]
        public virtual IActionResult FeedbackCreate([FromBody]Feedback feedback)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Feedback));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ProblemDetails));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(ProblemDetails));

            string exampleJson = null;
            exampleJson = "{\n  \"sentiment\" : 0.542,\n  \"rating\" : 4.0,\n  \"topic\" : 3,\n  \"comment\" : \"This is was really interesting\",\n  \"event\" : \"FOO12\"\n}";
            
            var example = exampleJson != null
            ? JsonSerializer.Deserialize<Feedback>(exampleJson)
            : default(Feedback);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This returns all feedback for a given event and topic</remarks>
        /// <param name="eventid">Id of event containing topic</param>
        /// <param name="topicid">Id of topic to leave feedback on</param>
        /// <response code="200">An array of feedback, empty array if topic or event not found</response>
        /// <response code="500">Unexpected error</response>
        [HttpGet]
        [Route("/api/feedback/{eventid}/{topicid}")]
        [ValidateModelState]
        [SwaggerOperation("FeedbackGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Feedback>), description: "An array of feedback, empty array if topic or event not found")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Unexpected error")]
        public virtual IActionResult FeedbackGet([FromRoute][Required]string eventid, [FromRoute][Required]int? topicid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Feedback>));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(ProblemDetails));

            string exampleJson = null;
            exampleJson = "[ {\n  \"sentiment\" : 0.542,\n  \"rating\" : 4.0,\n  \"topic\" : 3,\n  \"comment\" : \"This is was really interesting\",\n  \"event\" : \"FOO12\"\n}, {\n  \"sentiment\" : 0.542,\n  \"rating\" : 4.0,\n  \"topic\" : 3,\n  \"comment\" : \"This is was really interesting\",\n  \"event\" : \"FOO12\"\n} ]";
            
            var example = exampleJson != null
            ? JsonSerializer.Deserialize<List<Feedback>>(exampleJson)
            : default(List<Feedback>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
